# Change these first
owner: tally-llc # Your GitHub organization or username, where this repository lives
repo: tally-status # The name of this repository

sites:
  - name: Tally
    url: https://tally.llc
    headers:
      - "Authorization: Basic $TALLY_AUTH"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tally.llc
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/tally-llc/tally-status/master/static/img/icon.svg
  name: Tally
  introTitle: "**Tally** LLC formation, bank accounts, and compliance, all through a single API."
  introMessage: This is the official status page [https://tally.llc](https://tally.llc).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
