# Change these first
owner: tally-llc # Your GitHub organization or username, where this repository lives
repo: tally-status # The name of this repository

sites:
  - name: Tally Marketing Pages
    url: https://tally.llc
    headers:
      - "Authorization: Basic $TALLY_AUTH"
  - name: Tally App
    url: https://app.tally.llc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  publish: true
  cname: status.tally.llc
  # baseUrl: /your-repo-name
  name: Tally Status
  css: "footer { display: none; }"
  js: "document.querySelector('a.logo').href = 'https://tally.llc';"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
